export const environment = {
  production: true,
  baseURI: "http://172.104.175.74:8180/iconnect",
  path: {
    corporate_api: "/api/registration/corporate",
    college_api: "/api/registration/college",
    state_list: "/api/iconnect/state",
    country_list: "/api/iconnect/country",
    pendingapproval_list: "/api/iconnect/pendingapproval",
    loginService: "/api/login",
    signUpService: "/api/signUP",
    forgotPasswordService: "/api/forgetpassword",
    getAllColleges: "/api/collegeList",
    pendingApprovalByIdService: "/api/iconnect/pendingapproval",
    university_list: "/api/iconnect/universityList",
    add_college: "/api/college",
    add_corporate: "/api/corporate",
    changePassword: "/api/changePassword",
    pendingApprovalForStudentReg: "/api/placementofficer/pafsReg",
    pendingApprovalForStudentRegById: "/api/placementofficer/pafsRegById",
    student_api:"/api/student",
    job:"/api/hr/job",
    internship:"/api/hr/internship",
    hr_profile:"/api/hr/profile",
    placementOfficer:"/api/placementofficer",
    uploadFile:"/api/upload",
    locations:"/api/iconnect/location",
    locationByStateId: "/api/iconnect/location",
    companies:"/api/hr/companies",
    inviteCorporate: "/api/placementofficer/inviteCorporate",
    department: "/api/placementofficer/addDepartment",
    cources: "/api/iconnect/cources",
    streams: "/api/iconnect/stream/",
    jobtype: "/api/iconnect/jobtype/",
    percentage: "/api/iconnect/percentage/",
    notifyAdmin:"/api/placementofficer/notifyAdmin/",
    offers: "",
    stdInterviews: "",
    
    
  }
};
